### ISSUE TITLE
have a way to deploy/install all or one src/package

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-cli#4]
Just a feature request... to have some REST API to submit a JSON object to, and have the information inside that to download from a repo with ssh keys or token - if needed. Or be able to upload a *.gz file containing the entire repo and OS.js uploads/downloads it to its staging directory, extracts the contents and goes through the motions of `npm install` or `npm package:install`

**Comment by andersevenrud** [comment]
In the case of installable packages via the client, this is actually not the correct repository.

Running npm commands and the likes via HTTP APIs etc. might be a bit ugly because these are intended for deployment and not services in general.

This could be solved by having a separate registry for packages intalled via the client. The Package Manager stuff supports multiple sources, so this should be pretty trivial. This is actually on the TODO list, and I had it somewhat working on v2, so I'd like to have this again.

---

However, this is a task for the CLI as well, becaise having a  `package:install` command that could detect the following and install into a defined area (`src/packages` by default) would be nice:

* Git repo (url or ssh ending in `.git$`)
* Compressed archive (path)
* Directory (path)
* npm package (string)
* URL (`^(https?|ftp):`)

**Comment by andersevenrud** [comment]
As of now you can use git, npm, archives or whatever method preferred in the deployment-side of things (i.e. CLI) because you can just use your own utilities and use an arbitrary path for package discovery.

When it comes to doing this from the client and such, this issue will be used for that: https://github.com/os-js/osjs-client/issues/21
