### ISSUE TITLE
Create a clean remove package from CLI

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-cli#9]
Need a clean way to remove packages that were installed whether using npm or manually. A CLI command that can handle both cases would be nice. 👍 

Per Anders: 

> Anders Evenrud @andersevenrud 13:14
> npm remove mypackage npm run package:discover
> mkdir src/packages.disabled mv src/packages/MyPakage src/packages.disabled/ npm run package:discover
> I can probably add a shortcut script or something though.

**Comment by andersevenrud** [comment]
I started making this, and it got me thinking.... maybe it's better to add a configuration option to `src/cli/index.js` that allows for disabling packages is a better than making some sort of tasks that basically runs a couple of commands for you ?!

My thinking here is that I could instead add proper documentation on how to install and uninstall all different types of packages (via npm, for development, archives and git-repos) and then have this to disable instead of physically removing:

```
module.exports = {
  disable: [
    'Filemanager',
    'Draw'
  ],
  discover: [
    path.resolve(__dirname, '../packages')
  ],
  tasks: []
};
```

I'm a bit torn about this removal CLI thing because of the following:

1. It has to handle both regular filesystem installations and `npm`
2. For non-npm packages it would have to make the user confirm the removal or else work might be *destroyed*
3. It cannot run the discovery command automatically in some cases because of certain options the discovery command accepts (so these would have to be added to the removal command as well, and pass them over)


Your thoughts ?

**Comment by aherreraGH** [comment]
For #2, there isn't a simple command prompt "Are you sure?" Or you can drop the same console output as npm does, when using --force, "I hope you know what you're doing". Something like that. heh. You could add in your documentation in bold and red letters, "Warning: this command will wipe out for good the folder/package you submit for removal"

Just my thought on #2 there.

So, the disabling of a package is the same as a "soft delete". If I want the package to be completely removed from the src/packages, after the soft delete is done, I can just manually - at my own discretion - remove the package and no harm done, correct? What if I want to re-instate that package? Let's say I want to reinstall an updated version of the package, then I'll have to undo the soft delete that was set. Am I thinking correctly on that?

**Comment by andersevenrud** [comment]
> For #2, there isn't a simple command prompt "Are you sure?" Or you can drop the same console output as npm does, when using --force, "I hope you know what you're doing". Something like that. heh. You could add in your documentation in bold and red letters, "Warning: this command will wipe out for good the folder/package you submit for removal"

Sure, but I don't really see how this is a better method than doing it manually. It's the same amount of commands you have to run.


1. `npm remove packagename` or `mv src/packages/packagename ~/somewhere`
2. `npm run package:discover`

vs:

1. `npm remove PackageName`
2. `npm run package:discover`

Only when you're doing it manually there is no CLI script to blame if you deleted your stuff :laughing: 

> So, the disabling of a package is the same as a "soft delete". If I want the package to be completely removed from the src/packages, after the soft delete is done, I can just manually - at my own discretion - remove the package and no harm done, correct? What if I want to re-instate that package? Let's say I want to reinstall an updated version of the package, then I'll have to undo the soft delete that was set. Am I thinking correctly on that?

Yep.

And if we take this one step further (which applies to the top section of my comment), maybe adding `.disabled` to the folder name makes it also does the same thing ?

*Note* `npm run package:discover` **physically** removes all the traces from `dist/` if soft deleted or physically deleted.

**Comment by andersevenrud** [comment]
> I was thinking of a way to prevent myself from inadvertently deleting the wrong thing

You'd be in the same boat if you accidentally (or inadvertently) chose "Yes" in the CLI when it asks you for confirmation. :nerd_face: 

>  Also, having a consistent way to clear off applications/packages

This is the discovery command. It will link and unlink all packages detected.

> I don't want seen anymore within the directories of OS.js.

Adding to my first point, isn't it easier for you as a user to do this manually -- as you were the one that put it there in the first place ? I might be totally wrong here, but that's at least how I see it.

This might be one of the "consistency" things you're talking about, because the directory was maybe generated with `make:application`, etc. ?

> I think the .disabled is fine.

Cool

**Comment by aherreraGH** [comment]
> Adding to my first point, isn't it easier for you as a user to do this manually -- as you were the one that put it there in the first place ? I might be totally wrong here, but that's at least how I see it.

Eh, yeah. understood.

**Comment by andersevenrud** [comment]
> Eh, yeah. understood.

I'm not saying I'm ditching this though -- I just have to think about it a bit. I'll show you what I've come up with in a little bit.

**Comment by aherreraGH** [comment]
You, can ditch it, my feelings won't be hurt. lol
In all seriousness. I understood what you were getting at. I'll document it on my side the manual process for other devs who may take over my work.

**Comment by andersevenrud** [comment]
I've published a new release of `@osjs/cli` that adds the support for "soft deletion" (or disabling).

See commit message for details: https://github.com/os-js/osjs-cli/commit/38247a58643b54754902bccb47e54997d7a44efe

Also added some stuff from our discussion here: https://manual.os-js.org/v3/install/#remove-packages

**Comment by aherreraGH** [comment]
Excellent, thank you sir. 👍

**Comment by andersevenrud** [comment]
After letting this simmer for a while, I'm going to close this because I feel that introducing a CLI task for this doesn't really solve anything.

The two-step process for removing packages manually is much more obvious in its execution and prevents any accidental loss of data from my side :sweat_smile:

**Comment by aherreraGH** [comment]
I understand. Thank you for all the help you have provided.
